model: sevennet
device: cuda
fmax: 0.02
max_steps: 500
default_array_jobs: 10
write_partial: true
fullna_dir: data/example_fullNa
halfna_dir: data/example_halfNa
output_dir: results/sevennet
model_name: 7net-omat
